namespace Sqids;

#if NET7_0_OR_GREATER
/// <summary>
/// The configuration options for <see cref="SqidsEncoder{T}" />.
/// All properties are optional; any property that isn't explicitly specified will fall back to its
/// default value.
/// </summary>
#else
/// <summary>
/// The configuration options for <see cref="SqidsEncoder" />.
/// All properties are optional; any property that isn't explicitly specified will fall back to its
/// default value.
/// </summary>
#endif
public sealed class SqidsOptions
{
	/// <summary>
	/// Custom alphabet that will be used for the IDs.
	/// Must contain at least 5 characters.
	/// The default is lowercase letters, uppercase letters, and digits.
	/// </summary>
	public string Alphabet { get; set; } = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

	/// <summary>
	/// The minimum length for the IDs.
	/// The default is 0; meaning the IDs will be as short as possible.
	/// 255 is the maximum.
	/// </summary>
	public int MinLength { get; set; } = 0;

	/// <summary>
	/// List of blocked words that must not appear in the IDs.
	/// </summary>
	public HashSet<string> BlockList { get; set; } = new()
	{
		"aand",
		"ahole",
		"allupato",
		"anal",
		"anale",
		"anus",
		"arrapato",
		"arsch",
		"arse",
		"ass",
		"balatkar",
		"bastardo",
		"battona",
		"bitch",
		"bite",
		"bitte",
		"boceta",
		"boiata",
		"boob",
		"boobe",
		"bosta",
		"branlage",
		"branler",
		"branlette",
		"branleur",
		"branleuse",
		"cabrao",
		"cabron",
		"caca",
		"cacca",
		"cacete",
		"cagante",
		"cagar",
		"cagare",
		"cagna",
		"caraculo",
		"caralho",
		"cazzata",
		"cazzimma",
		"cazzo",
		"chatte",
		"chiasse",
		"chiavata",
		"chier",
		"chingadazos",
		"chingaderita",
		"chingar",
		"chingo",
		"chingues",
		"chink",
		"chod",
		"chootia",
		"chootiya",
		"clit",
		"clito",
		"cock",
		"coglione",
		"cona",
		"connard",
		"connasse",
		"conne",
		"couilles",
		"cracker",
		"crap",
		"culattone",
		"culero",
		"culo",
		"cum",
		"cunt",
		"damn",
		"deich",
		"depp",
		"dick",
		"dildo",
		"dyke",
		"encule",
		"enema",
		"enfoire",
		"estupido",
		"etron",
		"fag",
		"fica",
		"ficker",
		"figa",
		"foda",
		"foder",
		"fottere",
		"fottersi",
		"fotze",
		"foutre",
		"frocio",
		"froscio",
		"fuck",
		"gandu",
		"goo",
		"gouine",
		"grognasse",
		"harami",
		"haramzade",
		"hundin",
		"idiot",
		"imbecile",
		"jerk",
		"jizz",
		"kamine",
		"kike",
		"leccaculo",
		"mamahuevo",
		"mamon",
		"masturbate",
		"masturbation",
		"merda",
		"merde",
		"merdoso",
		"mierda",
		"mignotta",
		"minchia",
		"mist",
		"muschi",
		"neger",
		"negre",
		"negro",
		"nerchia",
		"nigger",
		"orgasm",
		"palle",
		"paneleiro",
		"patakha",
		"pecorina",
		"pendejo",
		"penis",
		"pipi",
		"pirla",
		"piscio",
		"pisser",
		"polla",
		"pompino",
		"poop",
		"porca",
		"porn",
		"porra",
		"pouffiasse",
		"prick",
		"pussy",
		"puta",
		"putain",
		"pute",
		"putiza",
		"puttana",
		"queca",
		"randi",
		"rape",
		"recchione",
		"retard",
		"rompiballe",
		"ruffiano",
		"sacanagem",
		"salaud",
		"salope",
		"saugnapf",
		"sbattere",
		"sbattersi",
		"sborra",
		"sborrone",
		"scheise",
		"scheisse",
		"schlampe",
		"schwachsinnig",
		"schwanz",
		"scopare",
		"scopata",
		"sexy",
		"shit",
		"slut",
		"spompinare",
		"stronza",
		"stronzo",
		"stupid",
		"succhiami",
		"sucker",
		"tapette",
		"testicle",
		"tette",
		"topa",
		"tringler",
		"troia",
		"trombare",
		"turd",
		"twat",
		"vaffanculo",
		"vagina",
		"verdammt",
		"verga",
		"wank",
		"wichsen",
		"xana",
		"xochota",
		"zizi",
		"zoccola"
	};
}
